### ISSUE TITLE
actual use

### ISSUE THREAD

**Issue by ppolicherla** [jackmu95/idle-timeout#4]
I am trying to use this package for my react app. And I am confused as how to actually build and use this package. for the constructor do I need to have a callback?? I just want to use this to monitor the inactivity and then logout if a certain amount of time of inactivity has gone by. 

const timeout = idleTimeout(
  () => {
    return;
  },
  {
    element: document,
    timeout: 1000 * 60 * 5,
    loop: false,
  },
);

that is my constructor but when I try to call the internal functions it gives me errors. Do i need to declare the functions i am using in the callback section?

**Comment by jacobmllr95** [comment]
@ppolicherla Yeah, the first argument need to be the callback where you can add you logging logic.

Make sure to set `loop: true` in the options when you want to get a callback every time the idle timeout is reached.
