### ISSUE TITLE
Not sure how to use this package...

### ISSUE THREAD

**Issue by joetidee** [jackmu95/idle-timeout#7]
Hi, I'm not clear on how to use this package. Does the callback function get fired once the idle state is reached? When using the `timeout` option, is it that after a set number milliseconds the callback will be fired if the idle state has not been reached? Or, is the `timeout` option the length of time the user must be idle for for the callback to be fired? Thanks in advance.

**Comment by KhaledMohamedP** [comment]
Yes, the callback gets called whenever the user is an idle state for the timeout specified in the setting
